# Docker Compose for TextExtract Pro

services:
  # Main web application
  textextract-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: textextract-pro
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://supabase.n8n-tech.cloud/functions/v1}
      - VITE_ENABLE_API=${VITE_ENABLE_API:-true}
    volumes:
      # Mount logs for monitoring
      - ./logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - textextract-network

  # Redis for caching (optional future enhancement)
  redis:
    image: redis:7-alpine
    container_name: textextract-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - textextract-network

networks:
  textextract-network:
    driver: bridge

volumes:
  redis_data:
    driver: local